export const alphabet = [
	{ letter: "А а", sound: "a", example: "Art", vowel: true, group: [1] },
	{ letter: "Ә ә", sound: "ä", example: "Jacket", vowel: true, group: [2] },
	{ letter: "Б б", sound: "b", example: "Bee", vowel: false, group: [5] },
	{ letter: "В в", sound: "v", example: "Vase", vowel: false, group: [5] },
	{ letter: "Г г", sound: "g", example: "Go", vowel: false, group: [5] },
	{ letter: "Ғ ғ", sound: "gh", example: "Ghoul", vowel: false, group: [5] },
	{ letter: "Д д", sound: "d", example: "Dog", vowel: false, group: [5] },
	{ letter: "Е е", sound: "ye", example: "Yes", vowel: true, group: [2] },
	{ letter: "Ё ё", sound: "yo", example: "Yolk", vowel: false, group: [] },
	{ letter: "Ж ж", sound: "zh", example: "Measure", vowel: false, group: [5] },
	{ letter: "З з", sound: "z", example: "Zoo", vowel: false, group: [4] },
	{ letter: "И и", sound: "i", example: "Igloo", vowel: true, group: [1, 2] },
	{ letter: "Й й", sound: "y", example: "Yacht", vowel: false, group: [3] },
	{ letter: "К к", sound: "k", example: "Kite", vowel: false, group: [5] },
	{ letter: "Қ қ", sound: "q", example: "Kite", vowel: false, group: [5] },
	{ letter: "Л л", sound: "l", example: "Lion", vowel: false, group: [3] },
	{ letter: "М м", sound: "m", example: "Mango", vowel: false, group: [3] },
	{ letter: "Н н", sound: "n", example: "Nose", vowel: false, group: [3] },
	{ letter: "Ң ң", sound: "ng", example: "Ring", vowel: false, group: [3] },
	{ letter: "О о", sound: "o", example: "Orange", vowel: true, group: [1] },
	{ letter: "Ө ө", sound: "o", example: "Orchid", vowel: true, group: [2] },
	{ letter: "П п", sound: "p", example: "Penguin", vowel: false, group: [5] },
	{ letter: "Р р", sound: "r", example: "Rabbit", vowel: false, group: [3] },
	{ letter: "С с", sound: "s", example: "Sun", vowel: false, group: [5] },
	{ letter: "Т т", sound: "t", example: "Tiger", vowel: false, group: [5] },
	{ letter: "У у", sound: "u", example: "Uber", vowel: true, group: [3] },
	{ letter: "Ү ү", sound: "u", example: "Cook", vowel: true, group: [2] },
	{ letter: "Ұ ұ", sound: "ü", example: "Suit", vowel: true, group: [1] },
	{ letter: "Ф ф", sound: "f", example: "Fox", vowel: false, group: [5] },
	{ letter: "Х х", sound: "kh", example: "Loch", vowel: false, group: [5] },
	{ letter: "Һ һ", sound: "h", example: "Horse", vowel: false, group: [5] },
	{ letter: "Ц ц", sound: "ts", example: "Tsar", vowel: false, group: [5] },
	{ letter: "Ч ч", sound: "ch", example: "Cherry", vowel: false, group: [5] },
	{ letter: "Ш ш", sound: "sh", example: "Shoe", vowel: false, group: [5] },
	{ letter: "Щ щ", sound: "shch", example: "Fresh", vowel: false, group: [5] },
	{ letter: "Ы ы", sound: "y", example: "Yurt", vowel: true, group: [1] },
	{ letter: "І і", sound: "i", example: "Igloo", vowel: true, group: [2] },
	{ letter: "Э э", sound: "e", example: "Elephant", vowel: true, group: [] },
	{ letter: "Ю ю", sound: "yu", example: "Yule", vowel: false, group: [] },
	{ letter: "Я я", sound: "ya", example: "Yard", vowel: false, group: [] },
	{
		letter: "Ь ь",
		sound: "Soft sign",
		example: "Soft mark in russian loaned words",
		vowel: false,
		group: [],
	},
	{
		letter: "Ъ ъ",
		sound: "Hard sign",
		example: "Hard mark in russian loaned words",
		vowel: false,
		group: [],
	},
] as const;
